// <auto-generated />
namespace FingerprintAttendance.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UserFingerPrintId_Nulls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserFingerPrintId_Nulls));
        
        string IMigrationMetadata.Id
        {
            get { return "202108010049085_UserFingerPrintId_Nulls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
